import { TrendingUp, Clock, Target } from 'lucide-react';

export default function Science() {
  return (
    <section id="science" className="py-16 md:py-24 bg-gray-50">
      <div className="max-w-6xl mx-auto px-4">
        <div className="text-center mb-12 md:mb-20">
          <h2 className="text-3xl md:text-4xl font-display font-bold text-navy-900 mb-4">
            The Science of Cellular Energy
          </h2>
          <p className="text-lg text-gray-700 max-w-2xl mx-auto">
            Your energy declines not from laziness, but from aging mitochondria. Understand the mechanism and the solution.
          </p>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center mb-16">
          <div>
            <h3 className="text-2xl md:text-3xl font-semibold text-navy-900 mb-6">
              Mitochondria: Your Cellular Power Plants
            </h3>
            <div className="space-y-5 text-gray-700">
              <p className="leading-relaxed">
                Mitochondria are microscopic organelles responsible for producing ATP—the universal energy currency of life. Every heartbeat, every thought, every movement depends on ATP generated by these cellular power plants.
              </p>
              <p className="leading-relaxed">
                Your body contains trillions of mitochondria. Energy-intensive tissues like your heart and brain pack them densely. When mitochondrial function declines with age, energy production plummets.
              </p>
              <p className="leading-relaxed">
                The result? Fatigue that coffee can't fix, mental fog, reduced motivation, and decreased physical capacity—even if you're healthy otherwise.
              </p>
              <p className="font-semibold text-teal-700">
                The good news: mitochondrial function can be supported and optimized at any age.
              </p>
            </div>
          </div>

          <div className="bg-white rounded-xl border border-gray-200 p-8 shadow-md">
            <h4 className="text-xl font-semibold text-navy-900 mb-8">How NAD+ Declines With Age</h4>
            <div className="space-y-6">
              {[
                { age: '20s', pct: 100, color: 'bg-teal-500' },
                { age: '40s', pct: 50, color: 'bg-teal-400' },
                { age: '60s', pct: 25, color: 'bg-teal-300' },
                { age: '80s', pct: 10, color: 'bg-teal-200' }
              ].map((item) => (
                <div key={item.age}>
                  <div className="flex justify-between mb-2">
                    <span className="text-sm font-medium text-gray-700">Age {item.age}</span>
                    <span className="text-sm font-semibold text-navy-900">{item.pct}%</span>
                  </div>
                  <div className="w-full bg-gray-200 rounded-full h-2.5">
                    <div className={`${item.color} h-2.5 rounded-full`} style={{width: `${item.pct}%`}}></div>
                  </div>
                </div>
              ))}
            </div>
            <p className="mt-6 text-xs text-gray-600">
              NAD+ is critical for energy production. Declining NAD+ is a primary driver of age-related fatigue and reduced vitality.
            </p>
          </div>
        </div>

        <div className="bg-white rounded-xl border border-gray-200 p-8 md:p-12 shadow-md">
          <h3 className="text-2xl md:text-3xl font-semibold text-navy-900 mb-8 text-center">
            Our Three-Pillar Approach
          </h3>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
            <div className="text-center">
              <div className="bg-teal-500/10 w-16 h-16 rounded-lg flex items-center justify-center mx-auto mb-4">
                <TrendingUp className="w-8 h-8 text-teal-600" />
              </div>
              <h4 className="text-lg font-semibold text-navy-900 mb-3">Boost NAD+</h4>
              <p className="text-gray-700 text-sm">
                Provide precursors to naturally elevate NAD+ levels and restore your cellular energy manufacturing capacity.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-teal-500/10 w-16 h-16 rounded-lg flex items-center justify-center mx-auto mb-4">
                <Target className="w-8 h-8 text-teal-600" />
              </div>
              <h4 className="text-lg font-semibold text-navy-900 mb-3">Optimize Function</h4>
              <p className="text-gray-700 text-sm">
                Supply essential cofactors and nutrients that keep the energy production process running efficiently and cleanly.
              </p>
            </div>

            <div className="text-center">
              <div className="bg-teal-500/10 w-16 h-16 rounded-lg flex items-center justify-center mx-auto mb-4">
                <Clock className="w-8 h-8 text-teal-600" />
              </div>
              <h4 className="text-lg font-semibold text-navy-900 mb-3">Protect & Repair</h4>
              <p className="text-gray-700 text-sm">
                Defend mitochondria from oxidative stress and support the cellular repair systems that keep them young.
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>
  );
}
